### ISSUE TITLE
(development): Knapparna fungerar inte när man startar ifrån senaste (development)- branchen 2024-09-19. Innan man refreshar

### ISSUE THREAD

**Issue by FelixEdenborgh** [Zocom-LIA/CmsCodeMonkeys#25]
Problem när man startar upp programmet och kör. Knapparna fungerar inte utan man måste refresha för att få dem att fungera igen.

**Comment by ulfbou** [comment]
Fixed by PR #31

**Comment by AndreasHC** [comment]
"Knapparna" är en oklar referens. Jag hittar ett stort antal knappar som fungerar precis som jag förväntar mig.

Täcker #26  alla knappar som uppvisar det här problemet, eller finns det fler?
