### ISSUE TITLE
(development) Manage Pages i SiteIndex och Edit Content i WebPagesIndex när man skapar en ny Site/WebPage

### ISSUE THREAD

**Issue by ulfbou** [Zocom-LIA/CmsCodeMonkeys#26]
När man skapar en ny Site länkar Manage Pages till SiteId = 0, dvs. den uppdateras med rätt SiteId efter att den skapats i DbContext. 
Motsvarande händer när man skapar en ny WebPage och Edit Content.

**Comment by ulfbou** [comment]
Fixed by PR #31

**Comment by AndreasHC** [comment]
Jag kan inte återskapa problemet med "Edit Content" på nuvarande developement, bara det med "Manage Pages".
